{
 "title": "IoT",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "raspberryPi",
    "label": "Raspberry Pi",
    "query": "SELECT id AS __value, CONCAT('ID: ',id,' - Name: ',name) AS __text FROM raspberry_pi"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  name AS \"IoT\"\nFROM\n  raspberry_pi\nWHERE\n  id = '$raspberryPi'"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  id as \"ID\",\n  name AS \"Name\"\nFROM\n  raspberry_pi\nWHERE\n  id = '$raspberryPi'"
    }
   ]
  },
  {
   "title": "Overall Stats",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \"telemetry_count\" AS \"# Messages\",\n  \"avg_distance\" AS \"Avg. Distance (cm)\",\n  \"avg_ping\" AS \"Avg. Ping (ms)\"\nFROM\n  iot_summary\nWHERE\n  \"raspberryPiId\" = '$raspberryPi'"
    }
   ]
  },
  { "title": "Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Distance",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  distance AS \"Distance (cm)\"\nFROM\n  telemetry\nWHERE\n  $__timeFilter(time)\n  AND \"raspberryPiId\" = '$raspberryPi'\nORDER BY\n  time;"
    }
   ]
  },
  {
   "title": "Telemetry",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n  time as \"Time\",\n  \"distance\" AS \"Distance (cm)\",\n  \"ping\" AS \"Ping (ms)\"\nFROM\n  telemetry\nWHERE\n  $__timeFilter(time) \n  AND \"raspberryPiId\" = '$raspberryPi'\nORDER BY time DESC"
    }
   ]
  },
  {
   "title": "Ping AWS IoT Core Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  ping AS \"Ping (cm)\"\nFROM\n  telemetry\nWHERE\n  $__timeFilter(time)\n  AND \"raspberryPiId\" = '$raspberryPi'\nORDER BY\n  time;"
    }
   ]
  }
 ]
}