{
 "title": "Tables",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Raspberry Pi",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "raspberry_pi schema",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  table_name,\n  column_name,\n  data_type\nFROM\n  information_schema.columns\nWHERE\n  table_name='raspberry_pi'"
      }
     ]
    },
    {
     "title": "raspberry_pi",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT * FROM raspberry_pi ORDER BY id;"
      }
     ]
    }
   ]
  },
  {
   "title": "Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "telemetry schema",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  table_name,\n  column_name,\n  data_type\nFROM\n  information_schema.columns\nWHERE\n  table_name='telemetry'"
      }
     ]
    },
    {
     "title": "telemetry (Limited to 100 rows)",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT * FROM telemetry ORDER BY time LIMIT 100;"
      }
     ]
    }
   ]
  },
  {
   "title": "Materialized Views",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "MV: iot_summary",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      { "rawSql": "SELECT * FROM iot_summary" }
     ]
    }
   ]
  }
 ]
}